version: 2

project_name: dots

builds:
  - id: dots
    main: .
    binary: dots
    env:
      - CGO_ENABLED=0
      - GOFLAGS=-mod=readonly
    flags:
      - -buildvcs=false
      - -trimpath
    mod_timestamp: "0"
    goos:
      - darwin
      - linux
    goarch:
      - arm64
      - amd64
    ignore:
      - goos: darwin
        goarch: amd64
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - id: dots
    ids:
      - dots
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds_info:
      owner: root
      group: root
      mtime: "1970-01-01T00:00:00Z"
    files:
      - src: README.md
        info:
          owner: root
          group: root
          mode: 0644
          mtime: "1970-01-01T00:00:00Z"
      - src: LICENSE
        info:
          owner: root
          group: root
          mode: 0644
          mtime: "1970-01-01T00:00:00Z"
      - src: examples/config.toml
        info:
          owner: root
          group: root
          mode: 0644
          mtime: "1970-01-01T00:00:00Z"
      - src: docs/man/*.1
        info:
          owner: root
          group: root
          mode: 0644
          mtime: "1970-01-01T00:00:00Z"

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  disable: true
